import { isoly } from "isoly"
import { File } from "fetch-blob/file"
import { fixtures } from "../fixtures"
import { weekmeter } from "../index"

globalThis.File = File

describe("Report.Project", () => {
	it("is", () => {
		const report: weekmeter.Report.Project = fixtures.report.project()
		expect(weekmeter.Report.Project.is(report)).toEqual(true)
	})
	it("csv", async () => {
		const report: weekmeter.Report.Project = fixtures.report.project()
		const csv: File = weekmeter.Report.Project.csv(report)
		expect(await csv.text()).toEqual(
			`organization,client,project,activity,email,date,time\n------o1,------c1,------p1,------a1,jessie@rocket.com,${isoly.Date.now()},8.00`
		)
		expect(csv.name).toEqual("2024-01-01-2024-12-31_clientcode_projectcode.csv")
		expect(csv.type).toEqual("text/csv")
		const emptyLineTest: weekmeter.Report.Project = {
			type: "project",
			times: [
				{
					type: "work",
					organization: "pZqRg3xk",
					email: "jessie@rocket.com",
					date: "2024-10-07",
					value: { hours: 8 },
					client: "proquse",
					project: "proquse",
					activity: "sprint",
					modified: { value: "2024-10-29T13:00:10.992Z", by: "jessie@rocket.com" },
				},
				{
					type: "work",
					organization: "pZqRg3xk",
					email: "jessie@rocket.com",
					date: "2024-10-08",
					value: { hours: 2 },
					client: "proquse",
					project: "proquse",
					activity: "overhead",
					modified: { value: "2024-10-29T12:59:52.792Z", by: "jessie@rocket.com" },
				},
				{
					type: "work",
					organization: "pZqRg3xk",
					email: "jessie@rocket.com",
					date: "2024-10-08",
					value: { hours: 6 },
					client: "proquse",
					project: "proquse",
					activity: "sprint",
					modified: { value: "2024-10-29T13:00:14.296Z", by: "jessie@rocket.com" },
				},
				{
					type: "work",
					organization: "pZqRg3xk",
					email: "jessie@rocket.com",
					date: "2024-10-11",
					value: { minutes: 30, hours: 8 },
					client: "proquse",
					project: "proquse",
					activity: "overhead",
					modified: { value: "2024-10-29T13:00:24.461Z", by: "jessie@rocket.com" },
				},
				{
					type: "work",
					organization: "pZqRg3xk",
					email: "jessie@rocket.com",
					date: "2024-10-15",
					value: { hours: 8 },
					client: "proquse",
					project: "proquse",
					activity: "sprint",
					modified: { value: "2024-10-29T13:02:52.780Z", by: "jessie@rocket.com" },
				},
				{
					type: "work",
					organization: "pZqRg3xk",
					email: "jessie@rocket.com",
					date: "2024-10-16",
					value: { hours: 8 },
					client: "proquse",
					project: "proquse",
					activity: "sprint",
					modified: { value: "2024-10-29T13:02:53.299Z", by: "jessie@rocket.com" },
				},
				{
					type: "work",
					organization: "pZqRg3xk",
					email: "jessie@rocket.com",
					date: "2024-10-17",
					value: { hours: 8 },
					client: "proquse",
					project: "proquse",
					activity: "sprint",
					modified: { value: "2024-10-29T13:02:53.868Z", by: "jessie@rocket.com" },
				},
				{
					type: "work",
					organization: "pZqRg3xk",
					email: "jessie@rocket.com",
					date: "2024-10-18",
					value: { hours: 8 },
					client: "proquse",
					project: "proquse",
					activity: "sprint",
					modified: { value: "2024-10-29T13:02:54.838Z", by: "jessie@rocket.com" },
				},
				{
					type: "work",
					organization: "pZqRg3xk",
					email: "jessie@rocket.com",
					date: "2024-10-21",
					value: { hours: 8 },
					client: "proquse",
					project: "proquse",
					activity: "sprint",
					modified: { value: "2024-10-29T13:02:57.832Z", by: "jessie@rocket.com" },
				},
				{
					type: "work",
					organization: "pZqRg3xk",
					email: "jessie@rocket.com",
					date: "2024-10-22",
					value: { hours: 8 },
					client: "proquse",
					project: "proquse",
					activity: "sprint",
					modified: { value: "2024-10-29T13:02:58.378Z", by: "jessie@rocket.com" },
				},
				{
					type: "work",
					organization: "pZqRg3xk",
					email: "jessie@rocket.com",
					date: "2024-10-23",
					value: { hours: 8 },
					client: "proquse",
					project: "proquse",
					activity: "sprint",
					modified: { value: "2024-10-29T13:02:59.034Z", by: "jessie@rocket.com" },
				},
				{
					type: "work",
					organization: "pZqRg3xk",
					email: "jessie@rocket.com",
					date: "2024-10-24",
					value: { hours: 8 },
					client: "proquse",
					project: "proquse",
					activity: "sprint",
					modified: { value: "2024-10-29T13:02:59.666Z", by: "jessie@rocket.com" },
				},
				{
					type: "work",
					organization: "pZqRg3xk",
					email: "jessie@rocket.com",
					date: "2024-10-25",
					value: { hours: 8 },
					client: "proquse",
					project: "proquse",
					activity: "sprint",
					modified: { value: "2024-10-29T13:03:00.635Z", by: "jessie@rocket.com" },
				},
				{
					type: "work",
					organization: "pZqRg3xk",
					email: "jessie@rocket.com",
					date: "2024-10-28",
					value: {},
					client: "proquse",
					project: "proquse",
					activity: "overhead",
					modified: { value: "2024-10-29T13:03:13.229Z", by: "jessie@rocket.com" },
				},
				{
					type: "work",
					organization: "pZqRg3xk",
					email: "jessie@rocket.com",
					date: "2024-10-28",
					value: { hours: 8 },
					client: "proquse",
					project: "proquse",
					activity: "sprint",
					modified: { value: "2024-10-29T13:03:23.463Z", by: "jessie@rocket.com" },
				},
				{
					type: "work",
					organization: "pZqRg3xk",
					email: "jessie@rocket.com",
					date: "2024-10-29",
					value: {},
					client: "proquse",
					project: "proquse",
					activity: "overhead",
					modified: { value: "2024-10-29T13:03:13.768Z", by: "jessie@rocket.com" },
				},
				{
					type: "work",
					organization: "pZqRg3xk",
					email: "jessie@rocket.com",
					date: "2024-10-29",
					value: { hours: 8 },
					client: "proquse",
					project: "proquse",
					activity: "sprint",
					modified: { value: "2024-10-29T13:03:24.312Z", by: "jessie@rocket.com" },
				},
				{
					type: "work",
					organization: "pZqRg3xk",
					email: "jessie@rocket.com",
					date: "2024-10-30",
					value: {},
					client: "proquse",
					project: "proquse",
					activity: "overhead",
					modified: { value: "2024-10-29T13:03:14.401Z", by: "jessie@rocket.com" },
				},
				{
					type: "work",
					organization: "pZqRg3xk",
					email: "jessie@rocket.com",
					date: "2024-10-30",
					value: {},
					client: "proquse",
					project: "proquse",
					activity: "sprint",
					modified: { value: "2024-10-29T13:03:19.242Z", by: "jessie@rocket.com" },
				},
				{
					type: "work",
					organization: "pZqRg3xk",
					email: "jessie@rocket.com",
					date: "2024-10-31",
					value: {},
					client: "proquse",
					project: "proquse",
					activity: "overhead",
					modified: { value: "2024-10-29T13:03:15.177Z", by: "jessie@rocket.com" },
				},
				{
					type: "work",
					organization: "pZqRg3xk",
					email: "jessie@rocket.com",
					date: "2024-10-31",
					value: {},
					client: "proquse",
					project: "proquse",
					activity: "sprint",
					modified: { value: "2024-10-29T13:03:18.638Z", by: "jessie@rocket.com" },
				},
			],
			client: "proquse",
			project: "proquse",
			modified: { value: "2024-11-08T13:17:09.082Z", by: "jessie@rocket.com" },
			dates: { start: "2024-10-01", end: "2024-10-31" },
		}
		expect(await weekmeter.Report.Project.csv(emptyLineTest).text()).toEqual(
			"organization,client,project,activity,email,date,time\npZqRg3xk,proquse,proquse,sprint,jessie@rocket.com,2024-10-07,8.00\npZqRg3xk,proquse,proquse,overhead,jessie@rocket.com,2024-10-08,2.00\npZqRg3xk,proquse,proquse,sprint,jessie@rocket.com,2024-10-08,6.00\npZqRg3xk,proquse,proquse,overhead,jessie@rocket.com,2024-10-11,8.50\npZqRg3xk,proquse,proquse,sprint,jessie@rocket.com,2024-10-15,8.00\npZqRg3xk,proquse,proquse,sprint,jessie@rocket.com,2024-10-16,8.00\npZqRg3xk,proquse,proquse,sprint,jessie@rocket.com,2024-10-17,8.00\npZqRg3xk,proquse,proquse,sprint,jessie@rocket.com,2024-10-18,8.00\npZqRg3xk,proquse,proquse,sprint,jessie@rocket.com,2024-10-21,8.00\npZqRg3xk,proquse,proquse,sprint,jessie@rocket.com,2024-10-22,8.00\npZqRg3xk,proquse,proquse,sprint,jessie@rocket.com,2024-10-23,8.00\npZqRg3xk,proquse,proquse,sprint,jessie@rocket.com,2024-10-24,8.00\npZqRg3xk,proquse,proquse,sprint,jessie@rocket.com,2024-10-25,8.00\npZqRg3xk,proquse,proquse,sprint,jessie@rocket.com,2024-10-28,8.00\npZqRg3xk,proquse,proquse,sprint,jessie@rocket.com,2024-10-29,8.00"
		)
	})
})
