import * as fixtures from "../fixtures"
import { weekmeter } from "../index"

describe("Report.Salary", () => {
	it("is", () => {
		const report: weekmeter.Report.Salary = fixtures.getReport.salary()
		expect(weekmeter.Report.Salary.is(report)).toEqual(true)
	})
	it("generate", () => {
		const times = fixtures.getTime(5)
		let report = weekmeter.Report.Salary.generate(times)
		expect(report.adjustment).toEqual(undefined)
		expect(report.total).toEqual({ hours: 200 })
		expect(report.sick.times.length).toEqual(5)
		expect(report.unpaid.times.length).toEqual(5)
		expect(report.parental.times.length).toEqual(5)
		expect(report.vacation.times.length).toEqual(5)
		expect(report.work.times.length).toEqual(5)
		expect(report.sick.total).toEqual({ hours: 40 })
		expect(report.unpaid.total).toEqual({ hours: 40 })
		expect(report.parental.total).toEqual({ hours: 40 })
		expect(report.vacation.total).toEqual({ hours: 40 })
		expect(report.work.total).toEqual({ hours: 40 })
		report = weekmeter.Report.Salary.generate(times, { adjustment: { hours: 5 } })
		expect(report.adjustment).toEqual({ hours: 5 })
		expect(report.total).toEqual({ hours: 205 })
		expect(report.sick.times.length).toEqual(5)
		expect(report.unpaid.times.length).toEqual(5)
		expect(report.parental.times.length).toEqual(5)
		expect(report.vacation.times.length).toEqual(5)
		expect(report.work.times.length).toEqual(5)
		expect(report.sick.total).toEqual({ hours: 40 })
		expect(report.unpaid.total).toEqual({ hours: 40 })
		expect(report.parental.total).toEqual({ hours: 40 })
		expect(report.vacation.total).toEqual({ hours: 40 })
		expect(report.work.total).toEqual({ hours: 40 })
	})
})
